### ISSUE TITLE
'Proposing as' editability

### ISSUE THREAD

**Issue by vs77bb** [kernel-community/convo-app#123]
As a host, I'd still like the ability to edit the 'Proposing As' field so that it can read something custom, even if it is tied to my profile / my account by default.

Default state: 'Proposing As' = name chosen for account (i.e. 'vivek') 
Edit state: I can change it to 'vivek & angela', 'kernel stewards', etc. 

<img width="285" alt="image" src="https://github.com/anggxyz/convo-app/assets/23297747/08004b7b-d20d-405d-9f0c-e234d56defad">

**Comment by probablyangg** [comment]
should be in https://github.com/kernel-community/convo-app/discussions/233
