### ISSUE TITLE
Preview Embeds For Convos 

### ISSUE THREAD

**Issue by vs77bb** [kernel-community/convo-app#148]
When I share a Convo, I want a unique URL link to generate with the title of the convo. The helper text, for now, coukd stilll read “The kernel of a conversation” or something “Kernel Convo” as it currently does on Slack. 

Next: each convo has its own image, potentially added by user / AI generated colorwaves depending on title, etc. But step one, without this, would already make a big difference.

**Comment by anggxyz** [comment]
merged https://github.com/kernel-community/convo-app/pull/177 with staging and broke something there, not sure what. will be looking into it

**Comment by anggxyz** [comment]
“The kernel of a conversation” is such a beautiful tagline

**Comment by anggxyz** [comment]
ok fixed in cf37a9ec11a2e4e3e314fbcd86764ec9026c8432! (closing the issue but taking the tagline with me)
