### ISSUE TITLE
Convo editing not working

### ISSUE THREAD

**Issue by aliyakernel** [kernel-community/convo-app#155]
Editing not working on Convo! I tried to update my '[Bird by Bird](https://www.convo.cafe/rsvp/e6xCH63l-Y)' convo to change the meeting link--in the description and in the field, but it did not seem to update. I changed the link from a Google meet to a Slack huddle, and I don't see the updates after hitting submit.

<img width="457" alt="Screenshot 2024-01-30 at 8 22 55 AM" src="https://github.com/anggxyz/convo-app/assets/156850497/bf82535d-5b04-4ca1-a21c-16c18becf80f">
<img width="1213" alt="Screenshot 2024-01-30 at 8 23 37 AM" src="https://github.com/anggxyz/convo-app/assets/156850497/349aa864-dca8-4c24-aaff-f3db0190c0c7">

**Comment by anggxyz** [comment]
the last fix i pushed here 80ba1bc384cbb0861ee9465e2f1eeb4312d507a6 should fix this
