### ISSUE TITLE
Add instructional text 'Expand to See RSVPs'

### ISSUE THREAD

**Issue by aliyakernel** [kernel-community/convo-app#169]
I don't think it's obvious/clear where organizers of a Convo event can see who RSVPed. Can we add instructional text next to the session date to say "Expand to See RSVPs/Signups." See image:

![Convo](https://github.com/kernel-community/convo-app/assets/156850497/fb8675c6-83a2-45ec-bf71-a6bc570f1a60)

And what about including emails here too?

**Comment by anggxyz** [comment]
added in 7a25c933e0b02d2ffe49eceba2e51c7b1047f618
