### ISSUE TITLE
shefi nits

### ISSUE THREAD

**Issue by anggxyz** [kernel-community/convo-app#170]
adding more here

**Comment by Must-be-Ash** [comment]
The login button needs margin space
![IMAGE 2024-03-01 16:11:46](https://github.com/kernel-community/convo-app/assets/105402607/c1821930-abaa-4a49-ae2b-3c80d827c8e9)

**Comment by anggxyz** [comment]
fixed in 83151e5400701024831ab0c847e4617305ba62e7
