### ISSUE TITLE
SheFi

### ISSUE THREAD

**Issue by Must-be-Ash** [kernel-community/convo-app#173]
WhiteLabel the site. The design is on Figma. Don't use the nav bar yet. I still need to complete it
<img width="627" alt="Screenshot 2024-03-03 at 13 49 25" src="https://github.com/kernel-community/convo-app/assets/105402607/47a45d23-23e5-4ab8-acb5-ec11b7d388aa">

**Comment by Must-be-Ash** [comment]
There is a gap in the corner of the pop-up nav bar
![IMG_4472](https://github.com/kernel-community/convo-app/assets/105402607/d316d751-e624-4825-bd79-f509a36739cb)

**Comment by Must-be-Ash** [comment]
Turn the "..." for the menu to a sandwich icon like the example below and put the 'login' there too (for mobile)
![IMG_4471](https://github.com/kernel-community/convo-app/assets/105402607/046c3db6-0b08-48a3-af8c-77f0b87b4e00)

**Comment by anggxyz** [comment]
https://www.figma.com/file/1B2CPjvtpwoVgQQIZQ0p3R/Convo-Design-Guide?type=design&node-id=3%3A4&mode=design&t=VNC2TTAaY2rqHZ3A-1
