### ISSUE TITLE
Mobile app very buggy, not able to read full content / RSVP there

### ISSUE THREAD

**Issue by aliyakernel** [kernel-community/convo-app#199]
![IMG_5424](https://github.com/kernel-community/convo-app/assets/156850497/5a803dbd-2c32-42ce-ae87-2d6c985cbec0)

![IMG_5425](https://github.com/kernel-community/convo-app/assets/156850497/414f0193-4856-4e18-a0b5-eb826c3a19c4)

**Comment by Ricy137** [comment]
I'm also using mobile but I didn't met the problem. Can you confirm that the problem still exists or provide more information of the device information 🙃 🙃 🙃 ? 
![mobile_k](https://github.com/user-attachments/assets/e815bf90-0025-49ac-8615-581532e8d2f3)
![mobile_k2](https://github.com/user-attachments/assets/1cb61fb9-c337-476d-a97f-4a26081ffa87)

**Comment by aliyakernel** [comment]
Doesn't seem to persist anymore!
