### ISSUE TITLE
Organizers See Email Addresses / Ability To Communicate With Their RSVPs

### ISSUE THREAD

**Issue by vs77bb** [kernel-community/convo-app#229]
As an event organizer, I'd like a way to communicate with the people who RSVP to my events.

It would help to ensure organizers can see an email list of all their attendees, perhaps a one click 'Email your RSVP's flow'.

**Comment by probablyangg** [comment]
closing this issue for the discussion created here - https://github.com/kernel-community/convo-app/discussions/233
