### ISSUE TITLE
add more descriptors to make fields clearer when proposing a convo

### ISSUE THREAD

**Issue by aliyakernel** [kernel-community/convo-app#252]
reference points:

- https://kernel-community.slack.com/archives/C02FCA9997H/p1721230572740329?thread_ts=1720714204.956109&cid=C02FCA9997H

<img width="553" alt="Screenshot 2024-07-17 at 11 50 33 AM" src="https://github.com/user-attachments/assets/65d235bb-a577-460a-ae83-13fe7d9213c5">

<img width="647" alt="Screenshot 2024-07-17 at 11 50 27 AM" src="https://github.com/user-attachments/assets/71728e8a-1be6-4665-be17-9f0fe843c2f2">

can we update the fields to be more descriptive? 

- add text next to field for length of time, write "Length of event in hours"
- add text next to field for number of seats available, write "Number of seats available, enter 0 for no limit"

**Comment by probablyangg** [comment]
removing this field with the next merge
